### ISSUE TITLE
Waymo dataset is a tar file. I don't see any frames

### ISSUE THREAD

**Issue by sarimmehdi** [Yao-Shao/Waymo_Kitti_Adapter#1]
Hello. I downloaded waymo dataset tar file. Inside the tar file, there are no images, just tfrecord files. What should I do now?

**Comment by tomaszkaliciak** [comment]
Hi.
You should put all those .tfrecords files inside waymo_dataset directory.

**Comment by Yao-Shao** [comment]
@tomaszkaliciak is right. Waymo uses its own data structure named .tfrecord and you should see the images after the conversion.
