### ISSUE TITLE
2D bounding box is inaccurate

### ISSUE THREAD

**Issue by dosemeion** [Yao-Shao/Waymo_Kitti_Adapter#5]
it should not use ‘frame.projected_lidar_labels’ for 2D bounding box
![Uploading image.png…](Accurated)
![Uploading image.png…](Author's)

**Comment by taofuyu** [comment]
can't see imgs

**Comment by taofuyu** [comment]
I draw the 2Dbox too, it's not right

**Comment by dosemeion** [comment]
> I draw the 2Dbox too, it's not right
Author's reply
‘ I used the projected lidar labels for 2d bbox, and maybe there is some bias through projection. You can ask Waymo for more details. You can also try camera labels rather than lidar's and it may work better if you want a precise bbox.’
