### ISSUE TITLE
Wrong lidar data transformation? 

### ISSUE THREAD

**Issue by RocketFlash** [Yao-Shao/Waymo_Kitti_Adapter#6]
Hi @Yao-Shao ! Thank you for your very helpful tool! I have a problem with converted lidar data. Apparently, the data from some lidars wasn't been converted into vehicle coordinate system. 3D visualization shows it: 

![Screenshot 2020-04-14 at 18 24 38](https://user-images.githubusercontent.com/7099937/79250472-5631a400-7e87-11ea-8e6d-25234131d902.png)
![Screenshot 2020-04-14 at 18 24 53](https://user-images.githubusercontent.com/7099937/79250484-5a5dc180-7e87-11ea-9c8c-16957ad2a1af.png)

On the 2D visualization it is clear that some points lie correctly, and some don't. 

![Screenshot 2020-04-14 at 19 29 41](https://user-images.githubusercontent.com/7099937/79250616-96912200-7e87-11ea-9c7a-02794efb820d.png)

I hope for your help.

**Comment by RocketFlash** [comment]
Problem was in waymo_open_dataset. Just rebuilded everything and it starts working

**Comment by Weijiang-Xiong** [comment]
Hello RocketFlash, I'm having the same trouble as you. 
It seems the lidar points are not calibrated, I tried to rebuild waymo_open_dataset, but it didn't work.
btw, can you tell me which one of waymo_open_dataset did you use? cuz there is one in the code folder, another in site-packages

**Comment by RocketFlash** [comment]
Hi @Weijiang-Xiong ! I don't remember exactly how I solved the problem, but the solution was to reinstall waymo_open_dataset. Maybe I changed tensorflow version. Also it is necessary to install tensorflow via pip, since I had problems with the installation with conda version of tensorflow. My advice is to try different versions of tensorflow installed via pip (1.15, 2.0, 2.1).

**Comment by Weijiang-Xiong** [comment]
> Hi @Weijiang-Xiong ! I don't remember exactly how I solved the problem, but the solution was to reinstall waymo_open_dataset. Maybe I changed tensorflow version. Also it is necessary to install tensorflow via pip, since I had problems with the installation with conda version of tensorflow. My advice is to try different versions of tensorflow installed via pip (1.15, 2.0, 2.1).

Thanks for that!
Acutually, I found a solution at  https://github.com/erksch/waymo-open-dataset-viewer.
it turns out my cuda memory almost overflowed.. and I have to turn off cuda device..
> If you had a GPU with a small RAM, misalignment between the LIDARs can happen. In this case, please try to run the websocket using CPU:
> 
> CUDA_VISIBLE_DEVICES="-1" python websocket.py --segments-dir path/to/segments
