### ISSUE TITLE
2D box is NOT right

### ISSUE THREAD

**Issue by taofuyu** [Yao-Shao/Waymo_Kitti_Adapter#7]
After runing adapter.py , I just write a script to draw 2D box of objects. But it looks not right.
![a](https://user-images.githubusercontent.com/13781923/79970945-44bf4c00-84c6-11ea-957e-7184197847d0.jpg)

**Comment by taofuyu** [comment]
In adapter.py, line 174:
for labels in frame.projected_lidar_labels:
I think these labels are not the accurate 2D bbox, but just a 2Dbox ties corresponding 3Dbox. Accurate 2Dbox is contained in frame.camera_labels. 
But I do not know how to align the same object in projected_lidar_labels and camera_labels, since the same object has defferent id in projected_lidar_labels and camera_labels.

**Comment by Yao-Shao** [comment]
Yes, it is exactly why I used the lidar labels rather than the camera labels for 2D Bbox. Maybe you can ask Waymo for more explanation and help.
