### ISSUE TITLE
how to tranform 3d points from one frame to another

### ISSUE THREAD

**Issue by hughlee815** [Yao-Shao/Waymo_Kitti_Adapter#9]
hi,
Yao-Shao,
thanks for your awesome work. may i ask a question about the transformation? how can man tranform 3d points from one frame to another(or is it even possible to do that?)
i know there is a 4x4 row major transform matrix. but it is 4x4. when we have points whose shape is (n, 3), how can we do the transform operation?
thanks for your reply in advance.

**Comment by Yao-Shao** [comment]
Hi @hughlee815. Just add "1" for the forth dimension, like (x, y, z) -> (x, y, z, 1) and then apply the transform matrix

**Comment by hughlee815** [comment]
hi,
thanks for your soon reply. i tried your solution immediately, it works very well. but i got another question---after applying the transform matrix with the boxes of the second frame, these new boxes i got didn't coincide with those of the first frame.
i am wondering whether i get any wrong? shouldn't those boxes of the two frames coincide?

**Comment by Yao-Shao** [comment]
What do you mean by "coincide"? Did you draw the two boxes on the same image? If so, ofcourse the two boxes won't coincide because they are in the diffrent frame and the image is in the camera frame. If you want to draw bounding boxes on the image, you should use the bbox in the camera frame only, otherwise the bbox will not work well with the ground truth.

**Comment by hughlee815** [comment]
Aha, thanks, i guess i understand why i am wrong. Just one thing I am still not so clear --- I transform points from the 9th frame (just an example) to the 1st frame by
`trans = np.dot(np.linalg.inv(frame_1_pose), frame_9_pose)    # frame_1_pose means the 4*4 transform matrics in frame 1`
`points = np.row_stack((frame_9_points, np.ones(points.shape[0])))`
`points_transformed = np.dot(points, trans)[:,:3]`
then i draw _points_transformed_ and also 3d boxes in frame 9(which are not transforemed) via mayavi in one figure. In theory, point objects should not be in these 3d boxes, since these points have been transformed, while the 3d boxes are not. But according to my experiment, these point objects are still in these boxes, like they have never been transformed. 
This result is a little hard for me to understand. If it's not too much trouble, could you please tell me why this happen or did I do anything wrong?
Thanks in advance.

**Comment by hughlee815** [comment]
thans so much. i finlly find it is my code problem, the method is perfect!!!   thanks once again. respect!
